namespace KSPM.Network.Chat.Group
{
    /// <summary>
    /// Class representing an N-M group where each user can deliver messages to every one on the group.
    /// </summary>
    public class NMChatGroup : PersistentChatGroup
    {
        /// <summary>
        /// Creates an empty NM group.
        /// </summary>
        public NMChatGroup()
            : base()
        {
        }

        /// <summary>
        /// Creates an empty NM group.
        /// </summary>
        /// <param name="id">The Id that must be assigned to the group.<b>This id overrides the one generated by the system.</b></param>
        public NMChatGroup(short id) : base()
        {
            ChatGroup.ChatGroupCounter = id;
            this.id = ChatGroup.ChatGroupCounter++;
            this.Name = string.Format("Chatgroup-{0}", this.id);
        }
    }
}
