namespace KSPM.Network.Chat.Group
{
    /// <summary>
    /// A Non-persistent NM chat group.
    /// </summary>
    public class NonPersistentNMChatgroup : NonPersistenChatGroup
    {
        /// <summary>
        /// Creates an empty group ready to use.
        /// </summary>
        public NonPersistentNMChatgroup()
            : base()
        {
        }

        /// <summary>
        /// Creates an empty group with the given Id.
        /// </summary>
        /// <param name="id">The id that must be assigned to the group.<b>This id overrides the one generated by the system.</b></param>
        public NonPersistentNMChatgroup( short id) : base()
        {
            ChatGroup.ChatGroupCounter = id;
            this.id = ChatGroup.ChatGroupCounter++;
            this.Name = string.Format("Chatgroup-{0}", this.id);
        }
    }
}
